DROP TABLE NORMAL_BOARD;

DROP SEQUENCE BOARDSEQ;

CREATE SEQUENCE BOARDSEQ;

CREATE TABLE NORMAL_BOARD(
	
	NORMAL_NUM NUMBER PRIMARY KEY,
	USER_NUM NUMBER NOT NULL,
	USER_NICKNAME VARCHAR2(100) NOT NULL,
	NORMAL_TITLE VARCHAR2(250) NOT NULL,
	NORMAL_CONTENT VARCHAR2(4000) NOT NULL,
	NORMAL_CATEGORY VARCHAR2(50) NOT NULL,
	NORMAL_COUNT NUMBER NOT NULL,
	NORMAL_DATE_CREATE DATE NOT NULL,
	NORMAL_DATE_UPDATE DATE NULL,
	NORMAL_PREMIUM VARCHAR2(2) NULL,
	
	CONSTRAINT PAY_CHK_NORMAL_PREMIUM CHECK(NORMAL_PREMIUM IN ('Y','N')),
	
	CONSTRAINT USER_FK FOREIGN KEY (USER_NUM) REFERENCES USER_INFO(USER_NUM)
	);

SELECT * FROM NORMAL_BOARD;

DROP TABLE COMMENT_BOARD;

DROP SEQUENCE GROUPSQ;

-- 자유게시판
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST01', 'test시작합니다1', 'FREE', 0, TO_DATE('2019-06-03 20:14:20','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST02', 'test시작합니다2', 'FREE', 0, TO_DATE('2019-06-01 09:32:32','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST03', 'test시작합니다3', 'FREE', 0, TO_DATE('2019-06-13 11:48:09','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST04', 'test시작합니다4', 'FREE', 0, TO_DATE('2019-06-07 21:56:11','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST05', 'test시작합니다5', 'FREE', 0, TO_DATE('2019-06-11 17:31:58','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'TEST06', 'test시작합니다6', 'FREE', 0, SYSDATE, NULL, 'N');

-- 인원모집
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST01', 'crew시작합니다1', 'CREW', 0, TO_DATE('2019-06-03 20:14:20','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST02', 'crew시작합니다2', 'CREW', 0, TO_DATE('2019-06-01 09:32:32','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST03', 'crew시작합니다3', 'CREW', 0, TO_DATE('2019-06-13 11:48:09','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST04', 'crew시작합니다4', 'CREW', 0, TO_DATE('2019-06-07 21:56:11','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST05', 'crew시작합니다5', 'CREW', 0, TO_DATE('2019-06-11 17:31:58','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'CREW_TEST06', 'crew시작합니다6', 'CREW', 0, SYSDATE, NULL, 'N');

-- 질문게시판
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST01', 'qa시작합니다1', 'QA', 0, TO_DATE('2019-06-03 20:14:20','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST02', 'qa시작합니다2', 'QA', 0, TO_DATE('2019-06-01 09:32:32','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST03', 'qa시작합니다3', 'QA', 0, TO_DATE('2019-06-13 11:48:09','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST04', 'qa시작합니다4', 'QA', 0, TO_DATE('2019-06-07 21:56:11','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST05', 'qa시작합니다5', 'QA', 0, TO_DATE('2019-06-11 17:31:58','YYYY-MM-DD HH24:MI:SS'), NULL, 'N');
INSERT INTO NORMAL_BOARD
VALUES(BOARDSEQ.NEXTVAL, 1, 'Toy', 'QA_TEST06', 'qa시작합니다6', 'QA', 0, SYSDATE, NULL, 'N');
	
SELECT * FROM NORMAL_BOARD WHERE NORMAL_CATEGORY = 'CREW';

SELECT NORMAL_TITLE, NORMAL_DATE_CREATE
FROM (SELECT * FROM NORMAL_BOARD WHERE NORMAL_CATEGORY = 'FREE' ORDER BY NORMAL_DATE_CREATE DESC)
<<<<<<< HEAD
WHERE ROWNUM <= 5;


SELECT RNUM, BOARDSEQ, NORMAL_NUM, USER_NUM, USER_NICKNAME, NORMAL_TITLE, NORMAL_CONTENT, NORMAL_CATEGORY, NORMAL_COUNT, NORMAL_DATE_CREATE, NORMAL_DATE_UPDATE, NORMAL_PREMIUM 
		FROM ((SELECT ROWNUM AS RNUM, BOARDSEQ, NORMAL_NUM, USER_NUM, USER_NICKNAME, NORMAL_TITLE, NORMAL_CONTENT, NORMAL_CATEGORY, NORMAL_COUNT, NORMAL_DATE_CREATE, NORMAL_DATE_UPDATE, NORMAL_PREMIUM
		FROM (SELECT BOARDSEQ, NORMAL_NUM, USER_NUM, USER_NICKNAME, NORMAL_TITLE, NORMAL_CONTENT, NORMAL_CATEGORY, NORMAL_COUNT, NORMAL_DATE_CREATE, NORMAL_DATE_UPDATE, NORMAL_PREMIUM ORDER BY NORMAL_NUM DESC))
=======
WHERE ROWNUM <= 5;
>>>>>>> master
