DROP
	TABLE
		SERVICE_BOARD;

DROP
	SEQUENCE SERVICE_BOARD;

CREATE
	SEQUENCE SERVICESEQ;

CREATE
	TABLE
		SERVICE_BOARD(SERVICE_NUM NUMBER PRIMARY KEY,
		USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM),
		SERVICE_TITLE VARCHAR2(250) NOT NULL,
		SERVICE_CONTENT VARCHAR2(4000) NOT NULL,
		SERVICE_DATE_CREATE DATE NOT NULL,
		SERVICE_DATE_UPDATE DATE NULL,
		SERVICE_GROUPNO NUMBER NOT NULL,
		SERVICE_GROUPSQ NUMBER NOT NULL,
		SERVICE_TITLETAB NUMBER NOT NULL,
		SERVICE_DEL VARCHAR2(2) NOT NULL,
		CONSTRAINT SERVICE_DEL_CHK CHECK (SERVICE_DEL IN ('Y',
		'N')));

SELECT * FROM SERVICE_BOARD;