
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

DROP TABLE ANSWERNEWBOARD;

CREATE SEQUENCE BOARDNOSQ;
CREATE SEQUENCE GROUPNOSQ;

--글번호, 그룹번호, 그룹순서, 제목탭, 삭제여부
--제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERNEWBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT ANSWER_DELFLAG_CHK CHECK(DELFLAG IN ('Y','N'))
);
-- N = 아직 삭제 안되었다.  Y = 삭제 된 글
INSERT INTO ANSWERNEWBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,'N',
'관리자','테스트글','테스트중입니다.',SYSDATE);

SELECT BOARDNO,GROUPNO,GROUPSQ,TITLETAB,DELFLAG,WRITER,TITLE,CONTENT,REGDATE FROM ANSWERNEWBOARD
ORDER BY GROUPNO DESC, GROUPSQ;