
DROP SEQUENCE MYMVCBOARDSEQ;
DROP TABLE MYMVCBOARD;

CREATE SEQUENCE MYMVCBOARDSEQ;

CREATE TABLE MYMVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MYMVCBOARD(SEQ, WRITER, TITLE, CONTENT, REGDATE)
VALUES(MYMVCBOARDSEQ.NEXTVAL, '관리자','TEST','TEST중입니다',SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM MYMVCBOARD;


DROP SEQUENCE MYMVCLOGINSEQ;
DROP TABLE MYMVCLOGIN;

CREATE SEQUENCE MYMVCLOGINSEQ;

CREATE TABLE MYMVCLOGIN(
   SEQ NUMBER NOT NULL,
   ID VARCHAR2(1000) NOT NULL,
   PW VARCHAR2(1000) NOT NULL,
   NAME VARCHAR2(2000) NOT NULL,
   ADDR VARCHAR2(4000) NOT NULL,
   PHONE VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(1000) NOT NULL,
   ENABLED VARCHAR2(2) NOT NULL,
   ROLE VARCHAR2(100) NOT NULL,
   CONSTRAINT MYMVCLOGIN_PK PRIMARY KEY(SEQ),
   CONSTRAINT MYMVCLOGIN_UQ_ID UNIQUE (ID),
   CONSTRAINT MYMVCLOGIN_UQ_PHONE UNIQUE (PHONE),
   CONSTRAINT MYMVCLOGIN_UQ_EMAIL UNIQUE (EMAIL),
   CONSTRAINT MYMVCLOGIN_CHECK_ENABLED CHECK(ENABLED IN('Y','N'))
);

INSERT INTO MYMVCLOGIN(SEQ,ID,PW,NAME,ADDR,PHONE,EMAIL,ENABLED,ROLE)
VALUES(MYMVCLOGINSEQ.NEXTVAL, 'admin', 'admin1234', '관리자', '서울시 강남구', '010-1234-5678','admin@admin.com','Y','ADMIN');

SELECT SEQ,ID,PW,NAME,ADDR,PHONE,EMAIL,ENABLED,ROLE FROM MYMVCLOGIN;