DROP TABLE AFTER_USER;
DROP SEQUENCE AFTER_USERSEQ;

CREATE SEQUENCE AFTER_USERSEQ;
CREATE TABLE AFTER_USER(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(100),
	PW VARCHAR2(100),
	REGDATE DATE
);

SELECT * FROM AFTER_USER;
SELECT FLOOR(SYSDATE - REGDATE) DA, ID FROM AFTER_USER WHERE ID = 'wnsdus';

INSERT INTO AFTER_USER VALUES(
	AFTER_USERSEQ.NEXTVAL, 'wnsdus', '123', '2019-03-23'
);
INSERT INTO AFTER_USER VALUES(
	AFTER_USERSEQ.NEXTVAL, 'rodumani', '123', '2019-05-23'
);
