DROP
	TABLE
		PRJ_IN_USER;

CREATE
	TABLE
		PRJ_IN_USER(USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE,
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM) ON DELETE CASCADE) ;

SELECT * FROM PRJ_IN_USER;

DELETE FROM PRJ_IN_USER;