
DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

--글 번호 시퀀스
CREATE SEQUENCE BOARDNOSEQ;
--그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSEQ;

--글번호, 그룹번호, 그룹내에서 순서, 제목띄어쓰기
--제목,내용,작성자,작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

--첫번째 글 작성 (첫번째 글이니까 1, 첫번째 글이라 들여쓰기 필요없으니 0)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,
'첫번째 글 입니다.', '1번글 내용', '유저1', SYSDATE);

--두번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,
'두번째 글 입니다.', '2번글 내용', '유저2', SYSDATE);

--두번째 글에 답변 작성(부모의 그룹번호랑 같아야 함.) 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, 
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1, --부모그룹순서에 + 1 
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1, --부모글로부터 한칸 탭
	'두번째 글 입니다.', '2번글에 대한 답변', '유저1', SYSDATE
);

--두번째 글 답변에 대한 답변.
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=3), --글 3번의 그룹번호 2가 호출됨
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=3)+1, --글 3번의 그룹순서 2에 +1
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=3)+1, --글 3번의 탭에 +1
	'두번째 글 입니다.','2번글답변글에 대한 답변','유저3',SYSDATE
);

--첫번째 글에 대한 답변
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	'첫번째 글 입니다.','1번글에 대한 답변', '유저4', SYSDATE
);

-- 2,2,1에 답변글을 다시 달기위해선 기존 답글과 GROUPSQ가 같아지는 혼선이 생기므로
-- 기존 2,2에 달린 글들의 GROUPSQ를 UPDATE해줘야 한다.
-- 두번째 글에 답변(2,2,1)
-- 부모글과 같은 그룹에서,
-- 부모글의 그룹순서보다 더 큰 순서를 가진 글들의 그룹순서를 +1
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD --부모와 같은 그룹번호 이면서
				WHERE BOARDNO = 2)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD --부모의 그룹순서보다 큰 아이들
				WHERE BOARDNO = 2);
--업데이트 후 2,2,1에 답변글 생성.
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	'두번째 글 입니다.','2번글에 대한 답변','유저5',SYSDATE
);

--답변을 달자.
--1) 답변달 때는 무조건 UPDATE 우선!!
--부모의 글과 같은 그룹에서,
--부모의 글의 그룹순서보다 더 큰 순서의 글들의 그룹순서를 +1

--2) INSERT
--부모와 같은 그룹번호,
--부모의 그룹순서+1
--부모의 제목띄어쓰기 +1

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;
