
DROP TABLE BIKE_DB;

-- {"NEW_ADDR":"대여소 주소","CONTENT_ID":"대여소번호",
-- "ADDR_GU":"구분","LONGITUDE":"경도","CRADLE_COUNT":"거치대수",
-- "LATITUDE":"위도","CONTENT_NM":"대여소명"}
CREATE TABLE BIKE_DB(
	ADDR_GU VARCHAR2(4000),	
	CONTENT_ID NUMBER PRIMARY KEY,
	CONTENT_NM VARCHAR2(4000),
	NEW_ADDR VARCHAR2(4000),
	CRADLE_COUNT NUMBER,
	LONGITUDE NUMBER,
	LATITUDE NUMBER
);
-- ADDR_GU, CONTENT_ID, CONTENT_NM, NEW_ADDR, CRADLE_COUNT, LONGITUDE, LATITUDE
SELECT * FROM BIKE_DB;


