
DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARDSQ;

CREATE SEQUENCE CALBOARDSQ;
--번호,ID,제목,내용,일정,날짜
CREATE TABLE CALBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(2000) NOT NULL,
	TITLE VARCHAR2(4000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM CALBOARD ORDER BY SEQ DESC;

-- 날짜별로 최대 3개씩만 가져오는 쿼리문. (rownum 활용)
-- ROW_NUMBER() OVER(PARTITION BY @ ORDER BY) 는
-- @로 GROUP BY, GROUP 별로 ROWNUM을 사용하는 QUERY문이다.
SELECT *
FROM (SELECT (ROW_NUMBER() OVER(
	PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE)) RN,
	SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
	FROM CALBOARD
	WHERE ID = 'kh' AND SUBSTR(MDATE,1,6)='201905')
WHERE RN BETWEEN 1 AND 3;