DROP TABLE PIPIBOARD;
DROP SEQUENCE PIPISEQ;

CREATE SEQUENCE PIPISEQ;

CREATE TABLE PIPIBOARD(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(1000) NOT NULL,
	MYPW VARCHAR2(1000) NOT NULL,
	MYHEART NUMBER NOT NULL,
	MYFULL NUMBER NOT NULL,
	MYSTAMINA NUMBER NOT NULL,
	MYCLEAN NUMBER NOT NULL,
	MYDATE DATE NOT NULL,
	MYALLDAY VARCHAR2(2) NOT NULL,
	MYDISEASE VARCHAR2(2) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT PIPIBOARD_PK PRIMARY KEY(MYNO),
	CONSTRAINT PIPIBOARD_UQ_ID UNIQUE(MYID),
	CONSTRAINT PIPIBOARD_CK_ALLDAY CHECK(MYALLDAY IN('D','N')),
	CONSTRAINT PIPIBOARD_CK_DESEASE CHECK(MYDISEASE IN('Y','N')),
	CONSTRAINT PIPIBOARD_CK_ENABLED CHECK(MYENABLED IN('Y','N'))
);

SELECT * FROM PIPIBOARD;

ALTER TABLE PIPIBOARD MODIFY(MYDATE NUMBER);

